all:
	g++ -o ants *.cpp -lGL -lSDL -lSDL_image -lGLU -std=c++11
debug:
	g++ -o ants -g *.cpp -lGL -lSDL -lSDL_image -lGLU -std=c++11
warnings:
	g++ -o ants -Wall -Wextra -Wno-missing-braces *.cpp -lGL -lSDL -lSDL_image -lGLU -std=c++11
